import palette from './palette';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  h1: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: '35px',
    letterSpacing: '-0.24px',
    lineHeight: '40px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  h2: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: '29px',
    letterSpacing: '-0.24px',
    lineHeight: '32px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  h3: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: '24px',
    letterSpacing: '-0.06px',
    lineHeight: '28px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  h4: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: '20px',
    letterSpacing: '-0.06px',
    lineHeight: '24px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  h5: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: '18px',
    letterSpacing: '-0.05px',
    lineHeight: '20px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  h6: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: '16px',
    letterSpacing: '-0.05px',
    lineHeight: '20px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  subtitle1: {
    color: palette.text.primary,
    fontSize: '16px',
    letterSpacing: '-0.05px',
    lineHeight: '25px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  subtitle2: {
    color: palette.text.secondary,
    fontWeight: 400,
    fontSize: '14px',
    letterSpacing: '-0.05px',
    lineHeight: '21px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  body1: {
    color: palette.text.primary,
    fontSize: '14px',
    letterSpacing: '-0.05px',
    lineHeight: '21px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  body2: {
    color: palette.text.secondary,
    fontSize: '12px',
    letterSpacing: '-0.04px',
    lineHeight: '18px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  button: {
    color: palette.text.primary,
    fontSize: '14px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },

  caption: {
    color: palette.text.secondary,
    fontSize: '11px',
    letterSpacing: '0.33px',
    lineHeight: '13px',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },
  overline: {
    color: palette.text.secondary,
    fontSize: '11px',
    fontWeight: 500,
    letterSpacing: '0.33px',
    lineHeight: '13px',
    textTransform: 'uppercase',
    fontFamily: ['Noto Sans Thai', 'Noto Sans'].join(','),
  },

};
